### ISSUE TITLE
Can't access admin side

### ISSUE THREAD

**Issue by kainatkiranrashid2** [mohamedsamara/mern-ecommerce#121]
Dear Mohamed Samara, 
First of all, thankyou for putting this on github.

Secondly, one issue I am facing , is that I am not able to get access admin portion of the website. Pls guide me how can I ?

I will be very much thankful to you for this

**Comment by karthikeyana** [comment]
Hi Please find details

Demo:

URL: https://mern-store-80201.herokuapp.com/

Admin Credential:
user name: [tfs123@yopmail.com](mailto:tfs123@yopmail.com)
password: tfs123

User Credential:
user name: [tfs@yopmail.com](mailto:tfs@yopmail.com)
password: tfs123

**Comment by mohamedsamara** [comment]
@kainatkiranrashid2 @afreedituttu This is a demo on how the admin panel looks like, [admin panel](https://mernstore-bucket.s3.us-east-2.amazonaws.com/admin.mp4). There is no way to log in as admin in the production environment because it has all control access to data. However, you can be an Admin when you run the project on your local machine, you might have to change DB role value of your account.

**Comment by mohamedsamara** [comment]
Closing this issue as discussed [here](https://github.com/mohamedsamara/mern-ecommerce/issues/121#issuecomment-1120500275).
