### ISSUE TITLE
POST http://localhost:8080/api/product/add 400 (Bad Request)

### ISSUE THREAD

**Issue by nanaasar** [mohamedsamara/mern-ecommerce#165]
Everything works fine except i am unable to add new products with images..  when i add a new product without any image, it creates the product successfully but when i add new phone with image, i get this error POST http://localhost:8080/api/product/add 400 (Bad Request).

what am i doing wrong and how can i solve that.

thanks in advance

**Comment by nanaasar** [comment]
AWS details has been add but still unable to upload images. http://localhost:8080/api/product/add 400 (Bad Request).

**Comment by mohamedsamara** [comment]
@nanaasar start with logging the actual error on this [line](https://github.com/mohamedsamara/mern-ecommerce/blob/master/server/routes/api/product.js#L319). It will log the error in details instead of the friendly error returned to the client. This could be missing AWS configuration, check if the [AWS](https://github.com/mohamedsamara/mern-ecommerce/blob/master/server/utils/storage.js#L5) storage [function](https://github.com/mohamedsamara/mern-ecommerce/blob/master/server/routes/api/product.js#L297) returns the url at least.

**Comment by nanaasar** [comment]
so made a small separate project to upload images to my aws s3 bucket with the same aws access key and secret key. it works and but the same credentials doesn't work with the mern ecommerce project..
 I am still facing the error "your request couldn't be processed, try again"

please help me out

**Comment by mohamedsamara** [comment]
@nanaasar This is AWS error. I haven't seen it before, not sure why it also says region null maybe try add that. Look up the error there could be something about your AWS S3 setup - [Error](http://support.ottomatik.io/en/articles/2345890-how-to-fix-s3-requesttimetooskewed-error).

**Comment by nanaasar** [comment]
@mohamedsamara thanks for your time and patience.. i have been able to fix it... it was caused by time zone difference. 
bless
