### ISSUE TITLE
SIGNUP ERROR

### ISSUE THREAD

**Issue by bharath2612** [mohamedsamara/mern-ecommerce#51]
i used these ports, do i need to change something? @karthikeyana 
<img width="1440" alt="Screenshot 2021-05-09 at 6 36 42 PM" src="https://user-images.githubusercontent.com/42945720/117573475-b7ad5c00-b0f5-11eb-8892-e7935312c0fc.png">
<img width="1440" alt="Screenshot 2021-05-09 at 6 38 22 PM" src="https://user-images.githubusercontent.com/42945720/117573484-c3008780-b0f5-11eb-8987-42b5c6cfa24b.png">

**Comment by karthikeyana** [comment]
could you please share the backend log

**Comment by movvasrikanth** [comment]
@bharath2612 try again by replacing localhost with 127.0.0.1 in .env

**Comment by bharath2612** [comment]
@mohamedsamara I tried, can y'all share a sample env file with all other important codes wiped out, keeping the URLs, please!

Thanks

**Comment by mohamedsamara** [comment]
@bharath2612 the only missing keys in [env file](https://github.com/mohamedsamara/mern-ecommerce/blob/master/.env.example) are the secrets because they are not shared across projects. The error in the screenshot is unclear. Can you please provide a screenshot of the terminal logs when you run the application?
